### ISSUE TITLE
meta-updater-qemux86-64 and ubuntu 16.04.5 docker image Qemu  error

### ISSUE THREAD

**Issue by viktor-mitin** [advancedtelematic/meta-updater-qemux86-64#27]
Hi,
I've built meta-updater with Yocto Thud (-m thud.xml) according to https://docs.ota.here.com/quickstarts/qemuvirtualbox.html with ubuntu 16.04.5 docker image. When I try to start it, it returns the next python error. Please note it works well with ubuntu 18.04.2 (on the host). I'm wondering how to resolve this issue. Is there any additional package to install not mentioned in the 'quickstarts' manual?

Update: the same issue reconstructed with Yocto Rocko compilation. So it looks like this issue is not connected to Yocto version itself.
Update2 the same issue reconstructed with Yocto Rocko compilation without docker (with ubuntu 16.04.5 host). So it looks like this issue is not connected to the docker environment as well.
```
c@3e31dc934d8e:~/w/myproject_qemu_thud/build$ ../meta-updater/scripts/run-qemu-ota
Launching core-image-minimal with mac address ca:fe:63:30:15:37
To connect via SSH:
 ssh -o StrictHostKeyChecking=no root@localhost -p 2222
To connect to the serial console:
 nc localhost 8990
Traceback (most recent call last):
  File "../meta-updater/scripts/run-qemu-ota", line 73, in <module>
    main()
  File "../meta-updater/scripts/run-qemu-ota", line 65, in main
    s = Popen(cmdline)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Thanks

**Comment by pattivacek** [comment]
It looks like the call to `Popen` is failing because of the `No such file or directory` error. Try running `run-qemu-ota` with the `-n` flag to print out the full qemu command line, then verify that the files it references really do exist.

**Comment by viktor-mitin** [comment]
Hi Patrick,
Please see the output with '-n' key below. The files script references exist.

```
c@3e31dc934d8e:~/w/myproject/build$ ../meta-updater/scripts/run-qemu-ota -n
Launching core-image-minimal with mac address ca:fe:0e:85:28:3d
To connect via SSH:
 ssh -o StrictHostKeyChecking=no root@localhost -p 2222
To connect to the serial console:
 nc localhost 8990
qemu-system-x86_64 -bios /home/c/w/myproject/build/tmp/deploy/images/qemux86-64/u-boot-qemux86-64.rom -drive file=/home/c/w/myproject/build/tmp/deploy/images/qemux86-64/core-image-minimal-qemux86-64-20190221144001.otaimg,if=ide,format=raw,snapshot=on -serial tcp:127.0.0.1:8990,server,nowait -m 1G -usb -device usb-tablet -show-cursor -vga std -net user,hostfwd=tcp:0.0.0.0:2222-:22,restrict=off -net nic,macaddr=ca:fe:0e:85:28:3d -serial stdio -cpu Haswell

c@3e31dc934d8e:~/w/myproject/build$ ll /home/c/w/myproject/build/tmp/deploy/images/qemux86-64/u-boot-qemux86-64.rom
lrwxrwxrwx 2 c c 32 Feb 19 13:03 /home/c/w/myproject/build/tmp/deploy/images/qemux86-64/u-boot-qemux86-64.rom -> u-boot-qemux86-64-2017.09-r0.rom
c@3e31dc934d8e:~/w/myproject/build$ ll /home/c/w/myproject/build/tmp/deploy/images/qemux86-64/u-boot-qemux86-64-2017.09-r0.rom
-rw-r--r-- 2 c c 1048576 Feb 19 13:03 /home/c/w/myproject/build/tmp/deploy/images/qemux86-64/u-boot-qemux86-64-2017.09-r0.rom
c@3e31dc934d8e:~/w/myproject/build$ ll /home/c/w/myproject/build/tmp/deploy/images/qemux86-64/core-image-minimal-qemux86-64-20190221144001.otaimg
-rw-r--r-- 1 c c 207096832 Feb 21 14:54 /home/c/w/myproject/build/tmp/deploy/images/qemux86-64/core-image-minimal-qemux86-64-20190221144001.otaimg
```
Thanks

**Comment by pattivacek** [comment]
Quite strange. It seems unlikely that this could be a missing dependency issue, but I suppose it is possible. One of our build machines is currently running Ubuntu 16.04.5 LTS and I've never had this issue, but if it were to have the unspecified dependency, we wouldn't notice the problem.

I don't have any great ideas right now, but could you try changing the version of python specified on the first line of `meta-updater/scripts/run-qemu-ota` to `python3` instead of `python`? Does that help?

**Comment by viktor-mitin** [comment]
Changing the version of python specified on the first line of `meta-updater/scripts/run-qemu-ota` to `python3` instead of `python` didn't help. I will check several more ideas soon.
```
c@3e31dc934d8e:~/w/myproject/build$ ../meta-updater/scripts/run-qemu-ota
Launching core-image-minimal with mac address ca:fe:13:29:47:e4
To connect via SSH:
 ssh -o StrictHostKeyChecking=no root@localhost -p 2222
To connect to the serial console:
 nc localhost 8990
Traceback (most recent call last):
  File "../meta-updater/scripts/run-qemu-ota", line 73, in <module>
    main()
  File "../meta-updater/scripts/run-qemu-ota", line 65, in main
    s = Popen(cmdline)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'qemu-system-x86_64'
```
Thanks

**Comment by pattivacek** [comment]
Oh, but the error message is more descriptive in this case: it implies the missing file is "qemu-system-x86_64". Do you have an executable on your system with that name?

**Comment by viktor-mitin** [comment]
Patrick, you are right, in this particular environment qemu package was missing. So probably it should be added to the manual as well https://docs.ota.here.com/quickstarts/qemuvirtualbox.html

sudo apt-get install gawk wget git-core diffstat unzip texinfo gcc-multilib default-jre build-essential chrpath parted socat libsdl1.2-dev xterm repo libpython2.7-dev **qemu**

Thanks

**Comment by pattivacek** [comment]
> So probably it should be added to the manual

Good idea. I've made a PR for it: https://github.com/advancedtelematic/ats-garage-docs/pull/77

**Comment by viktor-mitin** [comment]
Please add to the documentation several more observations :

https://docs.ota.here.com/quickstarts/automotive-grade-linux.html
AGL build fails to compile in case of Ubuntu 18.04 and it compiles well in case of Ubuntu 16.04

https://docs.ota.here.com/quickstarts/qemuvirtualbox.html
Qemu build works well with Yocto Thud in case of building it with repo '-m thud.xml' option. However, in case of 'cow' overlay usage it requires to backup original image before building the next update image.

Thanks

**Comment by pattivacek** [comment]
>  AGL build fails to compile in case of Ubuntu 18.04 and it compiles well in case of Ubuntu 16.04

Technically, I don't think Ubuntu 18.04 is officially supported by rocko, which is what AGL is still using if I recall correctly, so that's outside of our control. We use 18.04 internally plenty, and it should be fine for most things. Do you recall what didn't work? We probably can't do much about it, but it would be good to know about.

> Qemu build works well with Yocto Thud in case of building it with repo '-m thud.xml' option.

The quickstart guide is currently meant to be a simple introduction, so we expect readers of that to use the recommended release branch, currently rocko. However, I can discuss that internally if it's worth specifying the thud/master case.
